version: "3"

services:
  # 前端服务
  ve-blog-element:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    image: sparkinai-app:latest  # 设置新的镜像名称和标签
    container_name: sparkinai-app
    restart: always
    ports:
      - "5173:80"
